version: "3"
services:

    taco-database:
        container_name: taco-database
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: taco_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - 3306:3306

    taco-application:
        container_name: taco-application
        build:
            context: .
            dockerfile: Dockerfile_springboot
        environment:
            MYSQL_ADDRESS: taco-database
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: root
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - taco-database

    taco-ui:
        container_name: taco-ui
        build:
            context: .
            dockerfile: Dockerfile_angular
        ports:
            - 4200:4200
        restart: always
        depends_on:
            - taco-application

