spring:
  profiles:
    active:
      - prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taco_db?characterEncoding=UTF-8
    username: root
    password: root
    initialization-mode: always
